version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.20.0
    steps:
      - checkout
      - run:
          command: yarn install && yarn build
          name: Run install and build
      - run:
          command: yarn test
          name: Run tests

workflows:
  test_ecom:
    jobs:
      - build_and_test
