version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0
    steps:
      - checkout
      - run: |
          yarn install && yarn run build
  
  test:
    docker:
      - image: cimg/node:16.20.0
    steps:
      - run: |
        yarn test
